[2023-09-15T12:20:14.846+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: business_question.daily_earnings manual__2023-09-15T12:20:12.734012+00:00 [queued]>
[2023-09-15T12:20:14.857+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: business_question.daily_earnings manual__2023-09-15T12:20:12.734012+00:00 [queued]>
[2023-09-15T12:20:14.858+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-09-15T12:20:14.875+0000] {taskinstance.py:1350} INFO - Executing <Task(GenericTransfer): daily_earnings> on 2023-09-15 12:20:12.734012+00:00
[2023-09-15T12:20:14.884+0000] {standard_task_runner.py:57} INFO - Started process 1690 to run task
[2023-09-15T12:20:14.891+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'business_question', 'daily_earnings', 'manual__2023-09-15T12:20:12.734012+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/businesse.py', '--cfg-path', '/tmp/tmpu0xr6kfy']
[2023-09-15T12:20:14.904+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask daily_earnings
[2023-09-15T12:20:15.167+0000] {task_command.py:410} INFO - Running <TaskInstance: business_question.daily_earnings manual__2023-09-15T12:20:12.734012+00:00 [running]> on host 7b2f04a25b74
[2023-09-15T12:20:15.398+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Aldinoharyo' AIRFLOW_CTX_DAG_ID='business_question' AIRFLOW_CTX_TASK_ID='daily_earnings' AIRFLOW_CTX_EXECUTION_DATE='2023-09-15T12:20:12.734012+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-15T12:20:12.734012+00:00'
[2023-09-15T12:20:15.441+0000] {base.py:73} INFO - Using connection ID 'destination' for task execution.
[2023-09-15T12:20:15.620+0000] {base.py:73} INFO - Using connection ID 'final_destination' for task execution.
[2023-09-15T12:20:15.669+0000] {generic_transfer.py:77} INFO - Extracting data from destination
[2023-09-15T12:20:15.670+0000] {generic_transfer.py:78} INFO - Executing: 
 
    SELECT SUM("DailyEarnings") as "TotalEarning", ÏnvoiceDate
    FROM (
            SELECT "InvoiceDate", SUM("TotalPrice") as "DailyEarnings"
            FROM "artist_revenue"
            GROUP BY "InvoiceDate"
    ) as a
    
[2023-09-15T12:20:15.677+0000] {base.py:73} INFO - Using connection ID 'destination' for task execution.
[2023-09-15T12:20:15.729+0000] {sql.py:375} INFO - Running statement: 
    SELECT SUM("DailyEarnings") as "TotalEarning", ÏnvoiceDate
    FROM (
            SELECT "InvoiceDate", SUM("TotalPrice") as "DailyEarnings"
            FROM "artist_revenue"
            GROUP BY "InvoiceDate"
    ) as a
    , parameters: None
[2023-09-15T12:20:15.736+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/generic_transfer.py", line 86, in execute
    results = get_records(self.sql)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 235, in get_records
    return self.run(sql=sql, parameters=parameters, handler=fetch_all_handler)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "Ïnvoicedate" does not exist
LINE 2: ...   SELECT SUM("DailyEarnings") as "TotalEarning", ÏnvoiceDat...
                                                             ^
HINT:  Perhaps you meant to reference the column "a.InvoiceDate".

[2023-09-15T12:20:15.762+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=business_question, task_id=daily_earnings, execution_date=20230915T122012, start_date=20230915T122014, end_date=20230915T122015
[2023-09-15T12:20:15.784+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 12 for task daily_earnings (column "Ïnvoicedate" does not exist
LINE 2: ...   SELECT SUM("DailyEarnings") as "TotalEarning", ÏnvoiceDat...
                                                             ^
HINT:  Perhaps you meant to reference the column "a.InvoiceDate".
; 1690)
[2023-09-15T12:20:15.825+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-09-15T12:20:15.854+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
