[2023-09-15T12:20:40.147+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: business_question.daily_earnings manual__2023-09-15T12:15:34.774407+00:00 [queued]>
[2023-09-15T12:20:40.156+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: business_question.daily_earnings manual__2023-09-15T12:15:34.774407+00:00 [queued]>
[2023-09-15T12:20:40.157+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 2
[2023-09-15T12:20:40.173+0000] {taskinstance.py:1350} INFO - Executing <Task(GenericTransfer): daily_earnings> on 2023-09-15 12:15:34.774407+00:00
[2023-09-15T12:20:40.180+0000] {standard_task_runner.py:57} INFO - Started process 1702 to run task
[2023-09-15T12:20:40.184+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'business_question', 'daily_earnings', 'manual__2023-09-15T12:15:34.774407+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/businesse.py', '--cfg-path', '/tmp/tmpbf4620u9']
[2023-09-15T12:20:40.190+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask daily_earnings
[2023-09-15T12:20:40.255+0000] {task_command.py:410} INFO - Running <TaskInstance: business_question.daily_earnings manual__2023-09-15T12:15:34.774407+00:00 [running]> on host 7b2f04a25b74
[2023-09-15T12:20:40.347+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Aldinoharyo' AIRFLOW_CTX_DAG_ID='business_question' AIRFLOW_CTX_TASK_ID='daily_earnings' AIRFLOW_CTX_EXECUTION_DATE='2023-09-15T12:15:34.774407+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-15T12:15:34.774407+00:00'
[2023-09-15T12:20:40.358+0000] {base.py:73} INFO - Using connection ID 'destination' for task execution.
[2023-09-15T12:20:40.430+0000] {base.py:73} INFO - Using connection ID 'final_destination' for task execution.
[2023-09-15T12:20:40.472+0000] {generic_transfer.py:77} INFO - Extracting data from destination
[2023-09-15T12:20:40.473+0000] {generic_transfer.py:78} INFO - Executing: 
 
    SELECT SUM("DailyEarnings") as "TotalEarning", ÏnvoiceDate
    FROM (
            SELECT "InvoiceDate", SUM("TotalPrice") as "DailyEarnings"
            FROM "artist_revenue"
            GROUP BY "InvoiceDate"
    ) as a
    
[2023-09-15T12:20:40.481+0000] {base.py:73} INFO - Using connection ID 'destination' for task execution.
[2023-09-15T12:20:40.486+0000] {sql.py:375} INFO - Running statement: 
    SELECT SUM("DailyEarnings") as "TotalEarning", ÏnvoiceDate
    FROM (
            SELECT "InvoiceDate", SUM("TotalPrice") as "DailyEarnings"
            FROM "artist_revenue"
            GROUP BY "InvoiceDate"
    ) as a
    , parameters: None
[2023-09-15T12:20:40.488+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/generic_transfer.py", line 86, in execute
    results = get_records(self.sql)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 235, in get_records
    return self.run(sql=sql, parameters=parameters, handler=fetch_all_handler)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "Ïnvoicedate" does not exist
LINE 2: ...   SELECT SUM("DailyEarnings") as "TotalEarning", ÏnvoiceDat...
                                                             ^
HINT:  Perhaps you meant to reference the column "a.InvoiceDate".

[2023-09-15T12:20:40.499+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=business_question, task_id=daily_earnings, execution_date=20230915T121534, start_date=20230915T122040, end_date=20230915T122040
[2023-09-15T12:20:40.513+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 13 for task daily_earnings (column "Ïnvoicedate" does not exist
LINE 2: ...   SELECT SUM("DailyEarnings") as "TotalEarning", ÏnvoiceDat...
                                                             ^
HINT:  Perhaps you meant to reference the column "a.InvoiceDate".
; 1702)
[2023-09-15T12:20:40.558+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-09-15T12:20:40.587+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
